BEGIN;

-- 0) Case-insensitive text support for "name"
CREATE EXTENSION IF NOT EXISTS citext;

-- 1) Drop the old teams table and any dependent FKs (if any)
DROP TABLE IF EXISTS teams CASCADE;

-- 2) Create the correct table
CREATE TABLE IF NOT EXISTS teams (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           CITEXT NOT NULL,                            -- case-insensitive
  city           VARCHAR(128) NOT NULL,
  image_url      VARCHAR(512),
  thumbnail_url  VARCHAR(512),
  is_active      BOOLEAN NOT NULL DEFAULT TRUE,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by     INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,

  CONSTRAINT teams_name_unique UNIQUE (name),                -- unique across all teams
  CONSTRAINT teams_name_len_chk CHECK (char_length(btrim(name::text)) >= 2),
  CONSTRAINT teams_city_len_chk CHECK (char_length(btrim(city)) >= 2)
);

COMMIT;
