CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(50) UNIQUE NOT NULL,
    alias VARCHAR(50) NOT NULL,	
    hashed_password VARCHAR(255) NOT NULL,
    profile_image_url VARCHAR(255) DEFAULT 'default_profile.png',
    language VARCHAR(10) DEFAULT 'en',
    role VARCHAR(20) DEFAULT 'espectador',
    account_status VARCHAR(20) DEFAULT 'active',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    failed_login_attempts INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS leagues (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) UNIQUE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 0) Case-insensitive text support for "name"
CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE IF NOT EXISTS teams (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           CITEXT NOT NULL,                            -- case-insensitive
  city           VARCHAR(128) NOT NULL,
  image_url      VARCHAR(512),
  thumbnail_url  VARCHAR(512),
  is_active      BOOLEAN NOT NULL DEFAULT TRUE,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by     INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,  -- who created it

  CONSTRAINT teams_name_unique UNIQUE (name),                -- unique across all teams
  CONSTRAINT teams_name_len_chk CHECK (char_length(btrim(name::text)) >= 2),
  CONSTRAINT teams_city_len_chk CHECK (char_length(btrim(city)) >= 2)
);
