-- Migration: Create fantasy_teams table to separate from real teams
-- Date: 2025-10-31

BEGIN;

-- Use citext for case-insensitive name uniqueness within a league if available
CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE IF NOT EXISTS fantasy_teams (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            CITEXT NOT NULL,
    city            VARCHAR(128) NOT NULL,
    image_url       VARCHAR(512),
    thumbnail_url   VARCHAR(512),
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id         INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    league_id       INTEGER NOT NULL REFERENCES leagues(id) ON DELETE CASCADE
);

-- Enforce uniqueness of team name within a league (case-insensitive)
CREATE UNIQUE INDEX IF NOT EXISTS ux_fantasy_teams_league_name
  ON fantasy_teams (league_id, LOWER(name));

-- Helpful indexes
CREATE INDEX IF NOT EXISTS ix_fantasy_teams_league_id ON fantasy_teams (league_id);
CREATE INDEX IF NOT EXISTS ix_fantasy_teams_user_id ON fantasy_teams (user_id);

COMMIT;
