-- Migration: Create players table
-- Date: 2025-11-03

BEGIN;

-- Enable citext if not already enabled
CREATE EXTENSION IF NOT EXISTS citext;

-- Create players table
CREATE TABLE IF NOT EXISTS players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    position VARCHAR(64) NOT NULL,
    image_url VARCHAR(512),
    thumbnail_url VARCHAR(512),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    team_id BIGINT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,

    -- Constraints
    CONSTRAINT players_name_len_chk CHECK (char_length(btrim(name)) >= 2),
    CONSTRAINT players_position_len_chk CHECK (char_length(btrim(position)) >= 1),
    CONSTRAINT players_position_valid_chk CHECK (position IN ('QB', 'RB', 'WR', 'TE', 'K', 'DST', 'FLEX'))
);

-- Enforce uniqueness: one player name per team (case-insensitive)
CREATE UNIQUE INDEX IF NOT EXISTS ux_players_team_name
  ON players (team_id, LOWER(name));

-- Helpful indexes
CREATE INDEX IF NOT EXISTS ix_players_team_id ON players (team_id);
CREATE INDEX IF NOT EXISTS ix_players_created_by ON players (created_by);
CREATE INDEX IF NOT EXISTS ix_players_position ON players (position);

COMMIT;
