-- Migration: Create player_news table and add visible designation to players
-- Date: 2025-11-24

BEGIN;

-- Create player_news table
CREATE TABLE IF NOT EXISTS player_news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id BIGINT NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    author_id INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    summary VARCHAR(30) NOT NULL,
    text VARCHAR(300) NOT NULL,
    is_injury BOOLEAN NOT NULL DEFAULT FALSE,
    injury_type VARCHAR(10),
    changes JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- If the news refers to an injury, enforce allowed injury codes when provided
ALTER TABLE player_news
  ADD CONSTRAINT chk_player_news_injury_codes CHECK (
    injury_type IS NULL OR injury_type IN ('O', 'D', 'Q', 'P', 'FP', 'IR', 'PUP', 'SUS')
  );

-- If is_injury is true then injury_type must be present
ALTER TABLE player_news
  ADD CONSTRAINT chk_player_news_injury_required CHECK (
    (is_injury = false) OR (is_injury = true AND injury_type IS NOT NULL)
  );

-- Helpful indexes
CREATE INDEX IF NOT EXISTS ix_player_news_player_id ON player_news (player_id);
CREATE INDEX IF NOT EXISTS ix_player_news_created_at ON player_news (created_at DESC);

-- Add visible designation fields to players to allow quick display of last news designation
ALTER TABLE players
  ADD COLUMN IF NOT EXISTS visible_designation VARCHAR(10),
  ADD COLUMN IF NOT EXISTS visible_designation_updated_at TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS ix_players_visible_designation ON players (visible_designation);

COMMIT;
