-- Extensions
CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(50) UNIQUE NOT NULL,
    alias VARCHAR(50) NOT NULL,	
    hashed_password VARCHAR(255) NOT NULL,
    profile_image_url VARCHAR(255) DEFAULT 'default_profile.png',
    language VARCHAR(10) DEFAULT 'en',
    role VARCHAR(20) DEFAULT 'manager',
    account_status VARCHAR(20) DEFAULT 'active',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    failed_login_attempts INTEGER DEFAULT 0,
    last_activity TIMESTAMPTZ
);

-- Seasons
CREATE TABLE IF NOT EXISTS seasons (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    year INTEGER NOT NULL,
    week_count INTEGER NOT NULL,
    start_date TIMESTAMPTZ NOT NULL,
    end_date TIMESTAMPTZ NOT NULL,
    is_current BOOLEAN NOT NULL DEFAULT FALSE,
    created_by INTEGER REFERENCES users(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_one_current_season
  ON seasons ((CASE WHEN is_current THEN 1 ELSE NULL END));

-- Leagues
CREATE TABLE IF NOT EXISTS leagues (
  id SERIAL PRIMARY KEY,
  uuid UUID DEFAULT gen_random_uuid(),
  name VARCHAR(100) UNIQUE NOT NULL,
  description VARCHAR(1000),
  max_teams SMALLINT NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'pre_draft',
  allow_decimal_scoring BOOLEAN NOT NULL DEFAULT TRUE,
  playoff_format SMALLINT NOT NULL,           -- 4 or 6
  created_by INTEGER REFERENCES users(id) ON DELETE RESTRICT,
  season_id INTEGER REFERENCES seasons(id) ON DELETE RESTRICT,
  trade_deadline TIMESTAMPTZ,
  max_trades_per_team INTEGER,                -- NULL => unlimited
  max_free_agents_per_team INTEGER,           -- NULL => unlimited
  roster_schema JSONB NOT NULL,               -- default roster JSON
  scoring_schema JSONB NOT NULL,              -- default scoring JSON
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT leagues_name_len_chk CHECK (char_length(btrim(name)) BETWEEN 1 AND 100),
  CONSTRAINT leagues_max_teams_chk CHECK (max_teams IN (4,6,8,10,12,14,16,18,20)),
  CONSTRAINT leagues_status_chk CHECK (status IN ('pre_draft','draft','in_season','completed')),
  CONSTRAINT leagues_playoff_format_chk CHECK (playoff_format IN (4,6))
);

CREATE TABLE IF NOT EXISTS teams (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           CITEXT NOT NULL,
  city           VARCHAR(128) NOT NULL,
  image_url      VARCHAR(512),
  thumbnail_url  VARCHAR(512),
  is_active      BOOLEAN NOT NULL DEFAULT TRUE,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by     INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  league_id      INTEGER REFERENCES leagues(id) ON DELETE CASCADE,

  CONSTRAINT teams_name_len_chk CHECK (char_length(btrim(name::text)) >= 2),
  CONSTRAINT teams_city_len_chk CHECK (char_length(btrim(city)) >= 2)
);

-- Uniqueness rules
CREATE UNIQUE INDEX IF NOT EXISTS ux_teams_name_global
  ON teams (LOWER(name::text));

CREATE INDEX IF NOT EXISTS ix_teams_league_id ON teams (league_id);
CREATE INDEX IF NOT EXISTS ix_teams_created_by ON teams (created_by);


CREATE TABLE IF NOT EXISTS league_members (
    id SERIAL PRIMARY KEY,
    league_id INTEGER NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    team_id INTEGER NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    user_alias VARCHAR(50) NOT NULL,
    joined_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    -- Constraints de unicidad
    CONSTRAINT ux_league_members_user_league UNIQUE (league_id, user_id),
    CONSTRAINT ux_league_members_team UNIQUE (team_id),
    CONSTRAINT ux_league_members_alias_league UNIQUE (league_id, user_alias),
    
    -- Validación de alias
    CONSTRAINT league_members_alias_chk CHECK (char_length(btrim(user_alias)) >= 1)
);

-- Índices para mejorar consultas
CREATE INDEX IF NOT EXISTS ix_league_members_league_id ON league_members(league_id);
CREATE INDEX IF NOT EXISTS ix_league_members_user_id ON league_members(user_id);
CREATE INDEX IF NOT EXISTS ix_league_members_team_id ON league_members(team_id);